# K8S CLUSTER INIT (MASTER)

- name: Init cluster by kubeadm
  ansible.builtin.command: >
    kubeadm init
    --apiserver-advertise-address={{ ansible_host }}
    --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Copy config file (admin.conf) to user directory
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: Install Tigera (Calico)
  ansible.builtin.command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ignore_errors: true

- name: Download and modify Calico custom-resources (CIDR)
  ansible.builtin.shell: |
    curl -O https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/custom-resources.yaml
    sed -i 's/192.168.0.0\/16/10.244.0.0\/16/g' custom-resources.yaml
    kubectl create -f custom-resources.yaml
  args:
    chdir: "/home/{{ ansible_user }}"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ignore_errors: true

- name: Generate join command for worker nodes
  ansible.builtin.command: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  changed_when: false

- name: Set join_command variable
  ansible.builtin.set_fact:
    join_command: "{{ kubeadm_join_cmd.stdout }}"